set(__QT_DEPLOY_TARGET_PiRacerDashboard_FILE /Users/ahnhyunjun/Documents/PlatformIO/Projects/ADUINO/Dashboard/build-cmake-qt683/PiRacerDashboard.app/Contents/MacOS/PiRacerDashboard)
set(__QT_DEPLOY_TARGET_PiRacerDashboard_TYPE EXECUTABLE)
